# Generated by Django 3.0.5 on 2021-04-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TRP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=500)),
                ('mobile', models.IntegerField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('aadhar', models.IntegerField()),
                ('address', models.CharField(max_length=500)),
                ('pan', models.CharField(max_length=50)),
                ('company_name', models.CharField(max_length=500)),
                ('gstin', models.CharField(max_length=50)),
                ('bank_account_no', models.IntegerField()),
                ('upload', models.FileField(upload_to='docu')),
            ],
        ),
    ]
